contour:
  image:
    registry: ghcr.io
    repository: projectcontour/contour
    tag: v1.33.0
  replicaCount: 1
  envoy:
    image:
      registry: docker.io
      repository: envoyproxy/envoy
      tag: v1.35.2
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
